name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            node-version: 14.x
          - os: macos-latest
            node-version: 14.x
          - os: ubuntu-latest
            node-version: 10.x
          - os: ubuntu-latest
            node-version: 12.x
          - os: ubuntu-latest
            node-version: 14.x

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install, build, and test
      run: |
        yarn
        yarn run build
        yarn run test
      env:
        CI: true
